-- EJECUTAR CON USUARIO SYS
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; 
CREATE USER adminportal IDENTIFIED BY adminportal
	QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO adminportal;

-- Ejecutar con usuario 
CREATE TABLE USUARIO(
    ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    CONTRASENA VARCHAR2(15) NOT NULL,
    CORREO VARCHAR2(15),
    
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE EVENTO (
    ID_EVENTO NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    FECHA DATE NOT NULL,
    UBICACION VARCHAR2(50),
    
    CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO)
);

CREATE TABLE INSCRIPCION (
    ID_INSCRIPCION NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    FEHCA_INSCRIPCION DATE NOT NULL,
    ID_USUARIO NUMBER(10),
    ID_EVENTO NUMBER(10),
    
    CONSTRAINT PK_INSCRIPCION PRIMARY KEY (ID_INSCRIPCION),
    CONSTRAINT FK_USUARIO_INSCRIPCION FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_EVENTO_INSCRIPCION FOREIGN KEY (ID_EVENTO)
        REFERENCES EVENTO(ID_EVENTO)
);

CREATE TABLE ORGANIZADOR (
    ID_ORGANIZADOR NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(10) NOT NULL,
    CONTACTO VARCHAR2(25) NOT NULL,
    ID_EVENTO NUMBER(10),
    
    CONSTRAINT PK_ORGANIZADOR PRIMARY KEY (ID_ORGANIZADOR),
    CONSTRAINT FK_ORGANIZADOR_EVENTO FOREIGN KEY (ID_EVENTO)
        REFERENCES EVENTO(ID_EVENTO)
    
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    ID_EVENTO NUMBER(10),
    
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT FK_EVENTO_CATEGORIA FOREIGN KEY (ID_EVENTO)
        REFERENCES EVENTO(ID_EVENTO)
);